name: alda3ia
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+5

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  animated_button: ^0.2.0
  animated_text_kit: ^4.2.2
  audioplayers: ^3.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  flutter_launcher_icons: ^0.12.0
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^8.2.1
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  rename: ^2.1.1
  search_page: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/
    - assets/images/
    - assets/sounds/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
